markdown: kramdown
markdown_ext: markdown,mkd,mkdn,md
highlighter: rouge
permalink: /:year/:title/
safe: false
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
#production_url : http://sunghlin.github.com

baseurl: ''

# Setup
title:            sunghlin.github.io
description:      ''
url:              http://sunghlin.github.io

author:
  name:           'Sunghlin'
  url:            

paginate:         5